import {
  BarChart3,
  Beaker,
  Boxes,
  Building2,
  CheckCircle2,
  Download,
  Droplets,
  Factory,
  Feather,
  FileCheck2,
  FileText,
  Flame,
  FlaskConical,
  Gauge,
  Globe2,
  Leaf,
  Lock,
  Mountain,
  Package,
  PackageCheck,
  PackageSearch,
  Recycle,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Sprout,
  Thermometer,
  Users,
  Waves,
  Wind,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { IconKey } from "@/types/i18n";

export const iconMap: Record<IconKey, LucideIcon> = {
  barChart: BarChart3,
  beaker: Beaker,
  boxes: Boxes,
  building: Building2,
  check: CheckCircle2,
  download: Download,
  droplets: Droplets,
  factory: Factory,
  feather: Feather,
  fileCheck: FileCheck2,
  fileText: FileText,
  flame: Flame,
  flask: FlaskConical,
  globe: Globe2,
  gauge: Gauge,
  leaf: Leaf,
  lock: Lock,
  mountain: Mountain,
  package: Package,
  packageCheck: PackageCheck,
  packageSearch: PackageSearch,
  recycle: Recycle,
  shield: ShieldCheck,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  thermometer: Thermometer,
  users: Users,
  waves: Waves,
  wind: Wind,
};
